# Generated by Django 2.2.7 on 2019-11-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number1', models.IntegerField(default=0)),
                ('number2', models.IntegerField(default=0)),
                ('sum', models.IntegerField(default=0)),
            ],
        ),
    ]
